"""build_tools/gen_tools.py — Generate bartorch/tools/_generated.py.

Run this script at build time (or manually) to produce thin wrappers for
every BART CLI command.  The generated module is imported lazily by
``bartorch/tools/__init__.py``.

Usage
-----
From the repository root::

    python build_tools/gen_tools.py

Requirements
------------
A ``bart`` binary must be on ``$PATH``, **or** the C++ extension
``_bartorch_ext`` must be importable so that ``bart_command("--list", ...)``
can be called in-process.

If neither is available the script falls back to the built-in tool list
defined in ``_KNOWN_TOOLS`` and generates stubs for those.

Generated file
--------------
``bartorch/tools/_generated.py`` — one ``make_tool()``-based wrapper per
BART command.  The file is **gitignored** and should be regenerated whenever
the BART submodule is updated.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Fallback list of known BART tools (BART v1.0.00)
# ---------------------------------------------------------------------------

_KNOWN_TOOLS: list[str] = [
    "bitmask",
    "cabs",
    "caldir",
    "calib",
    "caltraj",
    "cc",
    "ccapply",
    "conv",
    "conj",
    "copy",
    "cpyphs",
    "creal",
    "crop",
    "delta",
    "ecalib",
    "ecaltwo",
    "estdelay",
    "estdims",
    "estmat",
    "estvar",
    "extract",
    "fft",
    "fftmod",
    "fftshift",
    "filter",
    "flatten",
    "flip",
    "fmac",
    "homodyne",
    "invert",
    "itsense",
    "join",
    "looklocker",
    "lrmatrix",
    "mandelbrot",
    "meanshape",
    "moba",
    "mobafit",
    "morphop",
    "multicfl",
    "nlinv",
    "noise",
    "normalize",
    "nrmse",
    "nufft",
    "nufftbase",
    "onehotenc",
    "pattern",
    "phantom",
    "pics",
    "pocsense",
    "poisson",
    "poly",
    "repmat",
    "reshape",
    "resize",
    "rmfreq",
    "rof",
    "rss",
    "sake",
    "saxpy",
    "scale",
    "sdot",
    "show",
    "signal",
    "slice",
    "spow",
    "squeeze",
    "ssa",
    "std",
    "svd",
    "tgv",
    "threshold",
    "toimg",
    "traj",
    "transpose",
    "twixread",
    "upat",
    "version",
    "walsh",
    "wave",
    "wavelet",
    "wavepsf",
    "whiten",
    "window",
    "zeros",
    "zexp",
]

# Tools that are explicitly wrapped with richer Python APIs in bartorch.tools
# and should not be overwritten by the auto-generated thin stubs.
_SKIP_TOOLS: set[str] = {
    "ecalib",
    "caldir",
    "fft",
    "phantom",
    "pics",
}


def _query_tool_list() -> list[str] | None:
    """Return the list of BART tools by calling ``bart --list``.

    Returns ``None`` if ``bart`` is not available.
    """
    try:
        result = subprocess.run(
            ["bart", "--list"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode == 0:
            return [t.strip() for t in result.stdout.splitlines() if t.strip()]
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass
    return None


def _generate(out_path: Path, tools: list[str]) -> None:
    """Write *out_path* with one ``make_tool()``-based wrapper per tool."""
    lines: list[str] = [
        '"""bartorch.tools._generated — Auto-generated BART CLI wrappers.',
        "",
        "Generated by ``build_tools/gen_tools.py``.  Do not edit by hand.",
        '"""',
        "",
        "from bartorch.tools._dispatch import make_tool",
        "",
    ]

    exported: list[str] = []
    for name in sorted(tools):
        if name in _SKIP_TOOLS:
            continue
        # Sanitise: BART tool names are lowercase alphanumeric + underscore.
        safe = name.replace("-", "_")
        lines.append(f"{safe} = make_tool({name!r})")
        exported.append(safe)

    lines.append("")
    lines.append("__all__ = [")
    for e in exported:
        lines.append(f"    {e!r},")
    lines.append("]")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {out_path} with {len(exported)} tool wrappers.")


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    out_path = repo_root / "bartorch" / "tools" / "_generated.py"

    tools = _query_tool_list()
    if tools:
        print(f"Queried {len(tools)} tools from 'bart --list'.")
    else:
        print("'bart' not found on $PATH; using built-in tool list.")
        tools = _KNOWN_TOOLS

    _generate(out_path, tools)
    return 0


if __name__ == "__main__":
    sys.exit(main())
