"""bartorch.tools._generated — Auto-generated BART CLI wrappers.

Generated by ``build_tools/gen_tools.py``.  Do not edit by hand.

Each function wraps one BART command.  All functions:

* Accept named keyword arguments matching each BART flag (with type hints).
* Are decorated with ``@bart_op`` for automatic ``complex64`` normalisation.
* Accept ``**extra_flags`` for flags not listed as named parameters.
* Return a plain ``complex64 torch.Tensor`` (or tuple) in C-order.
* Carry a CUDA compatibility note in their docstring.

Source-based generation: no (fallback stubs)

.. rubric:: Fourier Transforms

.. autosummary::
   :nosignatures:

   fft
   fftmod
   fftshift

.. rubric:: Simulation / Phantoms

.. autosummary::
   :nosignatures:

   phantom
   signal
   bloch

.. rubric:: Sampling / Trajectories

.. autosummary::
   :nosignatures:

   traj
   poisson
   pattern
   upat
   estdelay

.. rubric:: Non-Cartesian

.. autosummary::
   :nosignatures:

   nufft
   nufftbase

.. rubric:: Coil Processing

.. autosummary::
   :nosignatures:

   coils
   cc
   ccapply
   walsh
   whiten
   rss

.. rubric:: Calibration

.. autosummary::
   :nosignatures:

   ecalib
   caldir
   calmat
   ecaltwo
   estvar
   estdims

.. rubric:: Image Processing

.. autosummary::
   :nosignatures:

   resize
   reshape
   crop
   flip
   circshift
   transpose
   repmat
   join
   extract
   squeeze
   flatten
   copy
   slice
   fmac
   scale
   saxpy

.. rubric:: Wavelets / Sparsity

.. autosummary::
   :nosignatures:

   wavelet
   cdf97
   threshold
   tgv
   rof

.. rubric:: Low-Rank / Subspace

.. autosummary::
   :nosignatures:

   svd
   lrmatrix
   casorati
   ssa

.. rubric:: Iterative Algorithms

.. autosummary::
   :nosignatures:

   pics
   pocsense
   itsense
   sake
   nlinv
   moba
   mobafit

.. rubric:: Utilities

.. autosummary::
   :nosignatures:

   bitmask
   avg
   noise
   nrmse
   normalize
   std
   sdot
   zeros
   delta
   cabs
   carg
   creal
   conj
   cpyphs
   spow
   zexp
   poly
   calc
   invert
   window
   filter
   homodyne
   rmfreq
   mandelbrot

.. rubric:: Miscellaneous

.. autosummary::
   :nosignatures:

   affinereg
   compress
   conv
   estmat
   looklocker
   meanshape
   morphop
   multicfl
   onehotenc
   twixread
   wave
   wavepsf

"""

from __future__ import annotations

from typing import Any

import torch

from bartorch.core.graph import dispatch
from bartorch.core.tensor import bart_op


@bart_op
def affinereg(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``affinereg`` command.

    Run ``bart affinereg -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('affinereg', list(inputs), output_dims, **extra_flags)


@bart_op
def avg(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``avg`` command.

    Run ``bart avg -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('avg', list(inputs), output_dims, **extra_flags)


@bart_op
def bitmask(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``bitmask`` command.

    Run ``bart bitmask -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('bitmask', list(inputs), output_dims, **extra_flags)


@bart_op
def bloch(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``bloch`` command.

    Run ``bart bloch -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('bloch', list(inputs), output_dims, **extra_flags)


@bart_op
def cabs(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``cabs`` command.

    Run ``bart cabs -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('cabs', list(inputs), output_dims, **extra_flags)


@bart_op
def calc(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``calc`` command.

    Run ``bart calc -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('calc', list(inputs), output_dims, **extra_flags)


@bart_op
def caldir(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``caldir`` command.

    Run ``bart caldir -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('caldir', list(inputs), output_dims, **extra_flags)


@bart_op
def calmat(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``calmat`` command.

    Run ``bart calmat -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('calmat', list(inputs), output_dims, **extra_flags)


@bart_op
def carg(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``carg`` command.

    Run ``bart carg -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('carg', list(inputs), output_dims, **extra_flags)


@bart_op
def casorati(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``casorati`` command.

    Run ``bart casorati -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('casorati', list(inputs), output_dims, **extra_flags)


@bart_op
def cc(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``cc`` command.

    Run ``bart cc -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('cc', list(inputs), output_dims, **extra_flags)


@bart_op
def ccapply(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``ccapply`` command.

    Run ``bart ccapply -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('ccapply', list(inputs), output_dims, **extra_flags)


@bart_op
def cdf97(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``cdf97`` command.

    Run ``bart cdf97 -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('cdf97', list(inputs), output_dims, **extra_flags)


@bart_op
def circshift(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``circshift`` command.

    Run ``bart circshift -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('circshift', list(inputs), output_dims, **extra_flags)


@bart_op
def coils(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``coils`` command.

    Run ``bart coils -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('coils', list(inputs), output_dims, **extra_flags)


@bart_op
def compress(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``compress`` command.

    Run ``bart compress -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('compress', list(inputs), output_dims, **extra_flags)


@bart_op
def conj(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``conj`` command.

    Run ``bart conj -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('conj', list(inputs), output_dims, **extra_flags)


@bart_op
def conv(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``conv`` command.

    Run ``bart conv -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('conv', list(inputs), output_dims, **extra_flags)


@bart_op
def copy(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``copy`` command.

    Run ``bart copy -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('copy', list(inputs), output_dims, **extra_flags)


@bart_op
def cpyphs(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``cpyphs`` command.

    Run ``bart cpyphs -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('cpyphs', list(inputs), output_dims, **extra_flags)


@bart_op
def creal(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``creal`` command.

    Run ``bart creal -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('creal', list(inputs), output_dims, **extra_flags)


@bart_op
def crop(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``crop`` command.

    Run ``bart crop -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('crop', list(inputs), output_dims, **extra_flags)


@bart_op
def delta(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``delta`` command.

    Run ``bart delta -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('delta', list(inputs), output_dims, **extra_flags)


@bart_op
def ecalib(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``ecalib`` command.

    Run ``bart ecalib -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('ecalib', list(inputs), output_dims, **extra_flags)


@bart_op
def ecaltwo(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``ecaltwo`` command.

    Run ``bart ecaltwo -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('ecaltwo', list(inputs), output_dims, **extra_flags)


@bart_op
def estdelay(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``estdelay`` command.

    Run ``bart estdelay -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('estdelay', list(inputs), output_dims, **extra_flags)


@bart_op
def estdims(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``estdims`` command.

    Run ``bart estdims -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('estdims', list(inputs), output_dims, **extra_flags)


@bart_op
def estmat(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``estmat`` command.

    Run ``bart estmat -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('estmat', list(inputs), output_dims, **extra_flags)


@bart_op
def estvar(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``estvar`` command.

    Run ``bart estvar -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('estvar', list(inputs), output_dims, **extra_flags)


@bart_op
def extract(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``extract`` command.

    Run ``bart extract -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('extract', list(inputs), output_dims, **extra_flags)


@bart_op
def fft(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``fft`` command.

    Run ``bart fft -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('fft', list(inputs), output_dims, **extra_flags)


@bart_op
def fftmod(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``fftmod`` command.

    Run ``bart fftmod -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('fftmod', list(inputs), output_dims, **extra_flags)


@bart_op
def fftshift(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``fftshift`` command.

    Run ``bart fftshift -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('fftshift', list(inputs), output_dims, **extra_flags)


@bart_op
def filter(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``filter`` command.

    Run ``bart filter -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('filter', list(inputs), output_dims, **extra_flags)


@bart_op
def flatten(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``flatten`` command.

    Run ``bart flatten -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('flatten', list(inputs), output_dims, **extra_flags)


@bart_op
def flip(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``flip`` command.

    Run ``bart flip -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('flip', list(inputs), output_dims, **extra_flags)


@bart_op
def fmac(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``fmac`` command.

    Run ``bart fmac -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('fmac', list(inputs), output_dims, **extra_flags)


@bart_op
def homodyne(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``homodyne`` command.

    Run ``bart homodyne -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('homodyne', list(inputs), output_dims, **extra_flags)


@bart_op
def invert(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``invert`` command.

    Run ``bart invert -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('invert', list(inputs), output_dims, **extra_flags)


@bart_op
def itsense(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``itsense`` command.

    Run ``bart itsense -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('itsense', list(inputs), output_dims, **extra_flags)


@bart_op
def join(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``join`` command.

    Run ``bart join -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('join', list(inputs), output_dims, **extra_flags)


@bart_op
def looklocker(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``looklocker`` command.

    Run ``bart looklocker -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('looklocker', list(inputs), output_dims, **extra_flags)


@bart_op
def lrmatrix(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``lrmatrix`` command.

    Run ``bart lrmatrix -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('lrmatrix', list(inputs), output_dims, **extra_flags)


@bart_op
def mandelbrot(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``mandelbrot`` command.

    Run ``bart mandelbrot -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('mandelbrot', list(inputs), output_dims, **extra_flags)


@bart_op
def meanshape(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``meanshape`` command.

    Run ``bart meanshape -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('meanshape', list(inputs), output_dims, **extra_flags)


@bart_op
def moba(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``moba`` command.

    Run ``bart moba -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('moba', list(inputs), output_dims, **extra_flags)


@bart_op
def mobafit(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``mobafit`` command.

    Run ``bart mobafit -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('mobafit', list(inputs), output_dims, **extra_flags)


@bart_op
def morphop(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``morphop`` command.

    Run ``bart morphop -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('morphop', list(inputs), output_dims, **extra_flags)


@bart_op
def multicfl(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``multicfl`` command.

    Run ``bart multicfl -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('multicfl', list(inputs), output_dims, **extra_flags)


@bart_op
def nlinv(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``nlinv`` command.

    Run ``bart nlinv -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('nlinv', list(inputs), output_dims, **extra_flags)


@bart_op
def noise(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``noise`` command.

    Run ``bart noise -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('noise', list(inputs), output_dims, **extra_flags)


@bart_op
def normalize(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``normalize`` command.

    Run ``bart normalize -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('normalize', list(inputs), output_dims, **extra_flags)


@bart_op
def nrmse(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``nrmse`` command.

    Run ``bart nrmse -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('nrmse', list(inputs), output_dims, **extra_flags)


@bart_op
def nufft(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``nufft`` command.

    Run ``bart nufft -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('nufft', list(inputs), output_dims, **extra_flags)


@bart_op
def nufftbase(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``nufftbase`` command.

    Run ``bart nufftbase -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('nufftbase', list(inputs), output_dims, **extra_flags)


@bart_op
def onehotenc(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``onehotenc`` command.

    Run ``bart onehotenc -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('onehotenc', list(inputs), output_dims, **extra_flags)


@bart_op
def pattern(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``pattern`` command.

    Run ``bart pattern -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('pattern', list(inputs), output_dims, **extra_flags)


@bart_op
def phantom(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``phantom`` command.

    Run ``bart phantom -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('phantom', list(inputs), output_dims, **extra_flags)


@bart_op
def pics(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``pics`` command.

    Run ``bart pics -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('pics', list(inputs), output_dims, **extra_flags)


@bart_op
def pocsense(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``pocsense`` command.

    Run ``bart pocsense -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('pocsense', list(inputs), output_dims, **extra_flags)


@bart_op
def poisson(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``poisson`` command.

    Run ``bart poisson -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('poisson', list(inputs), output_dims, **extra_flags)


@bart_op
def poly(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``poly`` command.

    Run ``bart poly -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('poly', list(inputs), output_dims, **extra_flags)


@bart_op
def repmat(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``repmat`` command.

    Run ``bart repmat -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('repmat', list(inputs), output_dims, **extra_flags)


@bart_op
def reshape(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``reshape`` command.

    Run ``bart reshape -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('reshape', list(inputs), output_dims, **extra_flags)


@bart_op
def resize(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``resize`` command.

    Run ``bart resize -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('resize', list(inputs), output_dims, **extra_flags)


@bart_op
def rmfreq(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``rmfreq`` command.

    Run ``bart rmfreq -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('rmfreq', list(inputs), output_dims, **extra_flags)


@bart_op
def rof(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``rof`` command.

    Run ``bart rof -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('rof', list(inputs), output_dims, **extra_flags)


@bart_op
def rss(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``rss`` command.

    Run ``bart rss -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('rss', list(inputs), output_dims, **extra_flags)


@bart_op
def sake(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``sake`` command.

    Run ``bart sake -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('sake', list(inputs), output_dims, **extra_flags)


@bart_op
def saxpy(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``saxpy`` command.

    Run ``bart saxpy -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('saxpy', list(inputs), output_dims, **extra_flags)


@bart_op
def scale(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``scale`` command.

    Run ``bart scale -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('scale', list(inputs), output_dims, **extra_flags)


@bart_op
def sdot(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``sdot`` command.

    Run ``bart sdot -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('sdot', list(inputs), output_dims, **extra_flags)


@bart_op
def signal(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``signal`` command.

    Run ``bart signal -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('signal', list(inputs), output_dims, **extra_flags)


@bart_op
def slice(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``slice`` command.

    Run ``bart slice -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('slice', list(inputs), output_dims, **extra_flags)


@bart_op
def spow(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``spow`` command.

    Run ``bart spow -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('spow', list(inputs), output_dims, **extra_flags)


@bart_op
def squeeze(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``squeeze`` command.

    Run ``bart squeeze -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('squeeze', list(inputs), output_dims, **extra_flags)


@bart_op
def ssa(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``ssa`` command.

    Run ``bart ssa -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('ssa', list(inputs), output_dims, **extra_flags)


@bart_op
def std(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``std`` command.

    Run ``bart std -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('std', list(inputs), output_dims, **extra_flags)


@bart_op
def svd(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``svd`` command.

    Run ``bart svd -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('svd', list(inputs), output_dims, **extra_flags)


@bart_op
def tgv(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``tgv`` command.

    Run ``bart tgv -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('tgv', list(inputs), output_dims, **extra_flags)


@bart_op
def threshold(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``threshold`` command.

    Run ``bart threshold -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('threshold', list(inputs), output_dims, **extra_flags)


@bart_op
def traj(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``traj`` command.

    Run ``bart traj -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('traj', list(inputs), output_dims, **extra_flags)


@bart_op
def transpose(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``transpose`` command.

    Run ``bart transpose -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('transpose', list(inputs), output_dims, **extra_flags)


@bart_op
def twixread(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``twixread`` command.

    Run ``bart twixread -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('twixread', list(inputs), output_dims, **extra_flags)


@bart_op
def upat(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``upat`` command.

    Run ``bart upat -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('upat', list(inputs), output_dims, **extra_flags)


@bart_op
def walsh(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``walsh`` command.

    Run ``bart walsh -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('walsh', list(inputs), output_dims, **extra_flags)


@bart_op
def wave(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``wave`` command.

    Run ``bart wave -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('wave', list(inputs), output_dims, **extra_flags)


@bart_op
def wavelet(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``wavelet`` command.

    Run ``bart wavelet -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('wavelet', list(inputs), output_dims, **extra_flags)


@bart_op
def wavepsf(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``wavepsf`` command.

    Run ``bart wavepsf -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('wavepsf', list(inputs), output_dims, **extra_flags)


@bart_op
def whiten(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``whiten`` command.

    Run ``bart whiten -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('whiten', list(inputs), output_dims, **extra_flags)


@bart_op
def window(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``window`` command.

    Run ``bart window -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('window', list(inputs), output_dims, **extra_flags)


@bart_op
def zeros(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``zeros`` command.

    Run ``bart zeros -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('zeros', list(inputs), output_dims, **extra_flags)


@bart_op
def zexp(*inputs: torch.Tensor, output_dims: list[int] | None = None,
           **extra_flags: Any) -> torch.Tensor | tuple[torch.Tensor, ...]:
    """Wraps BART's ``zexp`` command.

    Run ``bart zexp -h`` for full documentation.

    Parameters
    ----------
    *inputs : torch.Tensor
        Positional tensor inputs.
    output_dims : list[int], optional
        Expected output shape.
    **extra_flags : Any
        BART flags forwarded directly.

    Returns
    -------
    torch.Tensor
    """
    return dispatch('zexp', list(inputs), output_dims, **extra_flags)


__all__ = [
    'affinereg',
    'avg',
    'bitmask',
    'bloch',
    'cabs',
    'calc',
    'caldir',
    'calmat',
    'carg',
    'casorati',
    'cc',
    'ccapply',
    'cdf97',
    'circshift',
    'coils',
    'compress',
    'conj',
    'conv',
    'copy',
    'cpyphs',
    'creal',
    'crop',
    'delta',
    'ecalib',
    'ecaltwo',
    'estdelay',
    'estdims',
    'estmat',
    'estvar',
    'extract',
    'fft',
    'fftmod',
    'fftshift',
    'filter',
    'flatten',
    'flip',
    'fmac',
    'homodyne',
    'invert',
    'itsense',
    'join',
    'looklocker',
    'lrmatrix',
    'mandelbrot',
    'meanshape',
    'moba',
    'mobafit',
    'morphop',
    'multicfl',
    'nlinv',
    'noise',
    'normalize',
    'nrmse',
    'nufft',
    'nufftbase',
    'onehotenc',
    'pattern',
    'phantom',
    'pics',
    'pocsense',
    'poisson',
    'poly',
    'repmat',
    'reshape',
    'resize',
    'rmfreq',
    'rof',
    'rss',
    'sake',
    'saxpy',
    'scale',
    'sdot',
    'signal',
    'slice',
    'spow',
    'squeeze',
    'ssa',
    'std',
    'svd',
    'tgv',
    'threshold',
    'traj',
    'transpose',
    'twixread',
    'upat',
    'walsh',
    'wave',
    'wavelet',
    'wavepsf',
    'whiten',
    'window',
    'zeros',
    'zexp',
]
