"""encoding_op — factory for persistent BART SENSE encoding operators."""

from __future__ import annotations

import torch

from bartorch.lib.linops import BartLinop


def encoding_op(
    maps: torch.Tensor,
    *,
    ksp_shape: tuple[int, ...] | None = None,
    pattern: torch.Tensor | None = None,
    traj: torch.Tensor | None = None,
    basis: torch.Tensor | None = None,
    cuda: bool | None = None,
) -> BartLinop:
    """Create a persistent BART SENSE encoding operator.

    Wraps BART's ``pics_model()`` library function to construct a Cartesian or
    non-Cartesian SENSE forward model that is persistent (constructed once and
    reused for multiple apply calls).

    Encoding models
    ---------------
    Cartesian (``traj=None``):
        ``E = P ∘ FFT ∘ coil-expansion``
        where ``P`` is the undersampling mask (omitted when ``pattern=None``).

    Non-Cartesian (``traj`` provided):
        ``E = NUFFT ∘ coil-expansion``

    With subspace (``basis`` provided):
        Subspace projection is prepended: ``E = … ∘ Φ``
        where ``Φ`` maps subspace coefficients to the temporal/echo dimension.

    Parameters
    ----------
    maps : torch.Tensor
        Sensitivity maps in bartorch C-order ``(nmaps, nc, [nz,] ny, nx)``,
        complex64.  Typically the output of :func:`bartorch.tools.ecalib`.
    ksp_shape : tuple[int, ...], optional
        K-space output shape in C-order.

        * Cartesian: ``(nc, [nz,] ny, nx)`` — inferred from ``maps`` if omitted.
        * Non-Cartesian: ``(nc, nspokes, nsamples, 1)`` — **must** be provided
          when ``traj`` is given.  The trailing ``1`` is required because BART's
          NUFFT stores each sample in a 1-element spatial dimension (the trivial
          x-dimension must be 1 in Fortran order).
    pattern : torch.Tensor, optional
        Undersampling mask (Cartesian), same spatial layout as k-space.
        ``None`` (default) means no masking (full k-space).
    traj : torch.Tensor, optional
        Non-Cartesian trajectory in C-order ``(..., 3)`` where the last
        dimension holds ``(kx, ky, kz)`` coordinates **normalised to**
        ``[-0.5, 0.5]`` (BART convention).  The trajectory generated by
        :func:`bartorch.tools.traj` already uses this normalisation.
        ``None`` (default) selects the Cartesian model.
    basis : torch.Tensor, optional
        Subspace basis in C-order ``(ncoeff, nt)`` where ``ncoeff`` is the
        number of subspace coefficients and ``nt`` is the number of
        echo/temporal frames.  ``None`` (default) disables subspace projection.
    cuda : bool or None, optional
        Device selection for the underlying BART operator:

        * ``None`` (default) — infer from the device of ``maps`` (or ``traj``
          if provided); CUDA if the tensor is already on GPU, CPU otherwise.
        * ``True``  — force GPU; requires a CUDA build of bartorch.  For
          non-Cartesian models this also enables GPU gridding
          (``pics_config.gpu_gridding = true``) so the NUFFT trajectory is
          moved to the GPU and the gridding step runs on the CUDA device.
        * ``False`` — force CPU.

        .. note::
            Off-resonance correction via time segmentation (B0 field map) is
            not yet exposed through :func:`encoding_op`.  It requires a
            separate API wrapper around BART's B0-correction linop, which is
            not accessible through ``pics_model()``.  This feature is planned
            for a future release.

    Returns
    -------
    BartLinop
        Persistent BART encoding operator.  Call :meth:`~BartLinop.forward`,
        :meth:`~BartLinop.adjoint`, :meth:`~BartLinop.normal`, or
        :meth:`~BartLinop.solve` to use it.

    Examples
    --------
    Cartesian SENSE (sensitivity maps from ecalib):

    >>> import bartorch.tools as bt
    >>> import bartorch.lib as bl
    >>> ksp  = bt.phantom([128, 128], kspace=True, ncoils=8)
    >>> sens = bt.ecalib(ksp, calib_size=24, maps=1)
    >>> E    = bl.encoding_op(sens)
    >>> img  = bt.phantom([128, 128])
    >>> ksp2 = E.forward(img)   # A x
    >>> img2 = E.adjoint(ksp2)  # A^H y

    Non-Cartesian SENSE:

    >>> traj = bt.traj(r=True, x=64, y=64)
    >>> E    = bl.encoding_op(sens, ksp_shape=(8, 64, 64, 1), traj=traj)
    """
    # Deferred import: avoids loading the C++ extension at module-import time,
    # which would fail if the extension hasn't been built yet.
    from bartorch._bartorch_ext import create_encoding_op  # noqa: PLC0415

    # Infer CUDA flag from the input tensor device when cuda=None.
    if cuda is None:
        ref = traj if traj is not None else maps
        cuda = ref.is_cuda

    handle = create_encoding_op(
        maps.to(torch.complex64),
        list(ksp_shape) if ksp_shape is not None else [],
        pattern,
        traj,
        basis,
        1 if cuda else 0,
    )
    return BartLinop(handle)
